-- Path to the jdtls binary generated by Mason
local mason_jdtls = vim.fn.stdpath("data") .. "/mason/bin/jdtls"

if vim.fn.executable(mason_jdtls) == 1 then
  vim.lsp.config('jdtls', {
    cmd = { mason_jdtls },
    root_markers = { "pom.xml", "build.gradle", "gradlew", "mvnw", ".git" },
  })
  vim.lsp.enable('jdtls')
end
